### ISSUE TITLE
Please do not make live requests in tests

### ISSUE THREAD

**Issue by Aneurysm9** [Sciencentistguy/emergence#9]
Love the library and really appreciate that you have not made the direct `fetch()` method public, ensuring that users use a cache.  Would it be possible to use a mock HTTP server in [this test](https://github.com/Sciencentistguy/emergence/blob/master/src/lib.rs#L137) to avoid what appears to be a request to the live AoC site during testing?  Thanks!

**Comment by Sciencentistguy** [comment]
I don't know much about HTTP mocking in rust, but I'll take a look at it - it sounds like a good idea :+1:
